---
title: "Report"
author: "Pranay Baid, Jordan Kallio"
date: "5/5/2023"
output: html_document
---

Word Limit: 750 words

Introduction: summarize the data you analyzed, the question you pursued, your statistical computation, and your conclusion
Body: describe your data (and its source, size, and cleaning), statistical computation, and results
Include graphical and numeric summaries to efficiently communicate your conclusion
Describe your statistical computation including the number of jobs you ran and the typical job time, memory, and disk space required
Mention weaknesses of your work
Conclusion: revisit your question and conclusion in the light of your report’s body. It could suggest future work.


	In conducting our project, we chose to analyze Amazon customer review data. Specifically, we wanted to discover the correlation between the sentiment of the words in reviews and the rating scores given. Furthermore, we wanted to investigate the difference in this correlation between several different product categories. The data we used was a public archive.zip from Kaggle, and contained within this file were 22 Gigabytes of data, organized into 37 .tsv files based on product categories. {discuss statistical computation and conclusion here}
	As aforementioned, we received our data from Kaggle. We did this by writing bash scripts to download archive.zip from its download link and then unpack it. From there, we used HPC slurm to run 37 parallel jobs which each processed one of the .tsv files. These jobs used the ‘readr’ package to read the .tsv file and the ‘dplyr’ package to perform preprocessing steps. Observations (reviews) in which there was no entry for the variable ‘review_body’ were removed, as our sentiment analysis relied on having a body of text to parse. Columns which were irrelevant to our analysis were dropped to pare down the data. The last step of preprocessing was data imputation, during which we filled in any remaining ‘NA’ values with the column’s median value.
	{discuss statistical computation at length here}
	{include visuals}
	One weakness of this particular data analysis project is that it uses a dataset which is unbalanced in regards to the number of observations for each rating score. There are significantly more reviews in which the customer awarded the product a ‘5’ than reviews with a ‘1’, ‘2’, ‘3’, or ‘4’, likely due to the fact that a customer is most likely to want to write a review for a product they were very pleased with. As a result, the results of our analysis may be biased towards that majority classification. Another weakness may be found in outliers in the dataset, in which observations with positive sentiments in their review body of text had rating scores that reflected the opposite.
